In [1]:
import pandas as pd
from pathlib import Path

EVENTS_DIR = Path("events")
TRANSFERS_DIR = Path("transfers")


events_df = pd.read_csv(EVENTS_DIR.joinpath("events.csv"))
game_info_df = pd.read_csv(EVENTS_DIR.joinpath("ginf.csv"))
event_game_info_df = pd.merge(events_df, game_info_df, on='id_odsp', how='inner')
transfers_df = pd.read_csv(TRANSFERS_DIR.joinpath("transfers.csv"))

In [2]:
player_name = 'Luis Suarez'

In [3]:
player_event_game_info = event_game_info_df[event_game_info_df['player'] == player_name.lower()]
player_event_game_info

,id_odsp,id_event,sort_order,time,text,event_type,event_type2,side,event_team,opponent,...,at,fthg,ftag,odd_h,odd_d,odd_a,odd_over,odd_under,odd_bts,odd_bts_n
331558,l89fA1AI/,l89fA1AI3,3,5,Luis Suarez (Liverpool) wins a free kick in th...,8,NaN,1,Liverpool,Crystal Palace,...,Crystal Palace,3,1,1.23,8.25,21.00,NaN,NaN,NaN,NaN
331571,l89fA1AI/,l89fA1AI16,16,13,"Goal! Goal! Liverpool 1, Crystal Palac...",1,12.0,1,Liverpool,Crystal Palace,...,Crystal Palace,3,1,1.23,8.25,21.00,NaN,NaN,NaN,NaN
331585,l89fA1AI/,l89fA1AI30,30,31,"Offside, Liverpool. Jose Enrique tries a throu...",9,13.0,1,Liverpool,Crystal Palace,...,Crystal Palace,3,1,1.23,8.25,21.00,NaN,NaN,NaN,NaN
331599,l89fA1AI/,l89fA1AI44,44,46,Attempt saved. Luis Suarez (Liverpool) right f...,1,NaN,1,Liverpool,Crystal Palace,...,Crystal Palace,3,1,1.23,8.25,21.00,NaN,NaN,NaN,NaN
331604,l89fA1AI/,l89fA1AI49,49,51,"Offside, Liverpool. Victor Moses tries a throu...",9,13.0,1,Liverpool,Crystal Palace,...,Crystal Palace,3,1,1.23,8.25,21.00,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939420,G0pLytmF/,G0pLytmF16,16,11,Attempt missed. Luis Suarez (Barcelona) right ...,1,12.0,2,Barcelona,Eibar,...,Barcelona,0,4,12.00,6.50,1.33,1.47,2.96,1.8,2.11
939426,G0pLytmF/,G0pLytmF22,22,20,Attempt missed. Luis Suarez (Barcelona) right ...,1,12.0,2,Barcelona,Eibar,...,Barcelona,0,4,12.00,6.50,1.33,1.47,2.96,1.8,2.11
939457,G0pLytmF/,G0pLytmF53,53,45,Luis Suarez (Barcelona) hits the right post wi...,1,12.0,2,Barcelona,Eibar,...,Barcelona,0,4,12.00,6.50,1.33,1.47,2.96,1.8,2.11
939471,G0pLytmF/,G0pLytmF69,69,68,"Goal! Eibar 0, Barcelona 3. Luis Suarez (Barc...",1,NaN,2,Barcelona,Eibar,...,Barcelona,0,4,12.00,6.50,1.33,1.47,2.96,1.8,2.11
939474,G0pLytmF/,G0pLytmF72,72,72,Attempt blocked. Luis Suarez (Barcelona) right...,1,12.0,2,Barcelona,Eibar,...,Barcelona,0,4,12.00,6.50,1.33,1.47,2.96,1.8,2.11

In [4]:
player_transfers = transfers_df[transfers_df['player_name'] == player_name]
player_transfers

Empty DataFrame
Columns: [league, season, window, team_id, team_name, team_country, dir, player_id, player_name, player_age, player_nation, player_nation2, player_pos, counter_team_id, counter_team_name, counter_team_country, transfer_fee_amnt, market_val_amnt, is_free, is_loan, is_loan_end, is_retired, transfer_id]
Index: []

[0 rows x 23 columns]

In [5]:
player_event_game_info.to_json(Path(player_name).with_suffix(".json"), orient='index', indent=2)