In [26]:
import random

import pandas as pd
from pathlib import Path

EVENTS_DIR = Path("events")

events_df = pd.read_csv(EVENTS_DIR.joinpath("events.csv"))
events_df

,id_odsp,id_event,sort_order,time,text,event_type,event_type2,side,event_team,opponent,...,player_in,player_out,shot_place,shot_outcome,is_goal,location,bodypart,assist_method,situation,fast_break
0,UFot0hit/,UFot0hit1,1,2,Attempt missed. Mladen Petric (Hamburg) left f...,1,12.0,2,Hamburg SV,Borussia Dortmund,...,NaN,NaN,6.0,2.0,0,9.0,2.0,1,1.0,0
1,UFot0hit/,UFot0hit2,2,4,"Corner, Borussia Dortmund. Conceded by Dennis...",2,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
2,UFot0hit/,UFot0hit3,3,4,"Corner, Borussia Dortmund. Conceded by Heiko ...",2,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
3,UFot0hit/,UFot0hit4,4,7,Foul by Sven Bender (Borussia Dortmund).,3,NaN,1,Borussia Dortmund,Hamburg SV,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
4,UFot0hit/,UFot0hit5,5,7,Gokhan Tore (Hamburg) wins a free kick in the ...,8,NaN,2,Hamburg SV,Borussia Dortmund,...,NaN,NaN,NaN,NaN,0,2.0,NaN,0,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941004,z5L2OT5E/,z5L2OT5E123,123,92,Lucas Torreira (Sampdoria) wins a free kick in...,8,NaN,2,Sampdoria,Atalanta,...,NaN,NaN,NaN,NaN,0,2.0,NaN,0,NaN,0
941005,z5L2OT5E/,z5L2OT5E124,124,93,"Corner, Sampdoria. Conceded by Andrea Masiello.",2,NaN,2,Sampdoria,Atalanta,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
941006,z5L2OT5E/,z5L2OT5E125,125,93,Attempt missed. Fabio Quagliarella (Sampdoria)...,1,12.0,2,Sampdoria,Atalanta,...,NaN,NaN,8.0,2.0,0,9.0,1.0,1,3.0,0
941007,z5L2OT5E/,z5L2OT5E126,126,94,Alberto Grassi (Atalanta) wins a free kick on ...,8,NaN,1,Atalanta,Sampdoria,...,NaN,NaN,NaN,NaN,0,4.0,NaN,0,NaN,0
941008,z5L2OT5E/,z5L2OT5E127,127,94,Foul by Pedro Pereira (Sampdoria).,3,NaN,2,Sampdoria,Atalanta,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0

In [27]:
game_info_df = pd.read_csv(EVENTS_DIR.joinpath("ginf.csv"))
game_info_df

,id_odsp,link_odsp,adv_stats,date,league,season,country,ht,at,fthg,ftag,odd_h,odd_d,odd_a,odd_over,odd_under,odd_bts,odd_bts_n
0,UFot0hit/,/soccer/germany/bundesliga-2011-2012/dortmund-...,True,2011-08-05,D1,2012,germany,Borussia Dortmund,Hamburg SV,3,1,1.56,4.41,7.42,NaN,NaN,NaN,NaN
1,Aw5DflLH/,/soccer/germany/bundesliga-2011-2012/augsburg-...,True,2011-08-06,D1,2012,germany,FC Augsburg,SC Freiburg,2,2,2.36,3.60,3.40,NaN,NaN,NaN,NaN
2,bkjpaC6n/,/soccer/germany/bundesliga-2011-2012/werder-br...,True,2011-08-06,D1,2012,germany,Werder Bremen,Kaiserslautern,2,0,1.83,4.20,4.80,NaN,NaN,NaN,NaN
3,CzPV312a/,/soccer/france/ligue-1-2011-2012/paris-sg-lori...,True,2011-08-06,F1,2012,france,Paris Saint-Germain,Lorient,0,1,1.55,4.50,9.40,NaN,NaN,NaN,NaN
4,GUOdmtII/,/soccer/france/ligue-1-2011-2012/caen-valencie...,True,2011-08-06,F1,2012,france,Caen,Valenciennes,1,0,2.50,3.40,3.45,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10107,xAkY8l6R/,/soccer/italy/serie-a/genoa-crotone-xAkY8l6R/,True,2017-01-22,I1,2017,italy,Genoa,Crotone,2,2,1.97,4.35,8.00,1.95,2.03,2.03,1.86
10108,xSU9scI9/,/soccer/england/premier-league/chelsea-hull-ci...,True,2017-01-22,E0,2017,england,Chelsea,Hull,2,0,1.19,8.50,20.00,1.54,2.68,2.40,1.66
10109,xY7uZwOI/,/soccer/france/ligue-1/monaco-lorient-xY7uZwOI/,True,2017-01-22,F1,2017,france,AS Monaco,Lorient,4,0,1.32,6.24,11.50,1.53,3.08,1.80,2.25
10110,YyeGxMX8/,/soccer/spain/laliga/betis-gijon-YyeGxMX8/,True,2017-01-22,SP1,2017,spain,Real Betis,Sporting Gijon,0,0,1.74,4.07,5.90,2.20,1.89,2.05,1.86
10111,z5L2OT5E/,/soccer/italy/serie-a/atalanta-sampdoria-z5L2O...,True,2017-01-22,I1,2017,italy,Atalanta,Sampdoria,1,0,1.79,3.96,5.40,1.90,2.07,1.80,2.16

In [28]:
PLAYERS = ["lionel messi", "cristiano ronaldo", "erling haaland", "zlatan ibrahimovic", "luis suarez"]
EVENT_TYPES = [1, 3, 4, 5]  # Attempt, foul, yellow card, second yellow card
COLUMNS = ["event_type", "event_team", "player", "is_goal", "location", "date", "season"]

full_df = pd.merge(events_df, game_info_df, how="left", on="id_odsp")

filtered_df = full_df[(full_df["player"].isin(PLAYERS)) & (full_df["event_type"].isin(EVENT_TYPES)) & (
        full_df["event_type2"] != 15) & (full_df["location"].notna()) & (full_df["location"] != 19)][COLUMNS]
filtered_df = filtered_df.replace(PLAYERS, [i.title() for i in PLAYERS])
filtered_df = filtered_df.replace(["Barcelona", "Manchester Utd"], ["FC Barcelona", "Manchester United"])
filtered_df

,event_type,event_team,player,is_goal,location,date,season
8144,1,Real Madrid,Cristiano Ronaldo,0,3.0,2011-08-28,2012
8149,1,Real Madrid,Cristiano Ronaldo,0,15.0,2011-08-28,2012
8152,1,Real Madrid,Cristiano Ronaldo,1,3.0,2011-08-28,2012
8156,1,Real Madrid,Cristiano Ronaldo,0,15.0,2011-08-28,2012
8159,1,Real Madrid,Cristiano Ronaldo,0,3.0,2011-08-28,2012
...,...,...,...,...,...,...,...
939440,1,FC Barcelona,Lionel Messi,0,15.0,2017-01-22,2017
939457,1,FC Barcelona,Luis Suarez,0,9.0,2017-01-22,2017
939462,1,FC Barcelona,Lionel Messi,1,3.0,2017-01-22,2017
939471,1,FC Barcelona,Luis Suarez,1,11.0,2017-01-22,2017
939474,1,FC Barcelona,Luis Suarez,0,11.0,2017-01-22,2017

The field used to map locations to x and y coordinates https://publications.fifa.com/en/football-stadiums-guidelines/technical-guideline/stadium-guidelines/pitch-dimensions-and-surrounding-areas/.

In the mapping the pitch is viewed with the short sides on the left and right. Origin is in the lower left corner.

First the mapping is done in yards where X = [0, 115] and Y = [0, 74] then the coordinates is scaled on the unitary square where X = [0, 1] and Y = [0 ,1].

In [29]:
coordinates = {"x": [], "y": []}
for index, row in filtered_df.iterrows():
    location = row["location"]
    match location:
        case 1:  # Attacking half
            x = random.randrange(58, 115)
            y = random.randrange(0, 74)
        case 2:  # Defensive half
            x = random.randrange(0, 57)
            y = random.randrange(0, 74)
        case 3: # Centre of the box
            x = random.randrange(97, 109)
            y = random.randrange(27, 47)
        case 4: # Left wing
            x = random.randrange()
            y = random.randrange()
        case 5: # Right wing
            x = random.randrange(58, 115)
            y = random.randrange(0, 15)
        case 6: # Difficult angle and long range
            x = random.randrange(58, 97)
            y = random.choice([random.randrange(0, 15), random.randrange(59, 74)])
        case 7: # Difficult angle on the left
            x = random.randrange(70, 97)
            y = random.randrange(59, 74)
        case 8: # Difficult angle on the right
            x = random.randrange(70, 97)
            y = random.randrange(0, 15)
        case 9: # Left side of the box
            x = random.randrange(97, 115)
            y = random.randrange(59, 74)
        case 10: # Left side of the six yard box
            x = random.randrange(109, 115)
            y = random.randrange(53, 59)
        case 11: # Right side of the box
            x = random.randrange(97, 115)
            y = random.randrange(0, 15)
        case 12: # Right side of the six yard box
            x = random.randrange(109, 115)
            y = random.randrange(15, 21)
        case 13: # Very close range
            x = random.randrange(112, 115)
            y = random.randrange(30, 44)
        case 14: # Penalty shot
            x = 105
            y = 37
        case 15: # Outside the box
            x = random.randrange(86, 97)
            y = random.randrange(15, 59)
        case 16: # Long range
            x = random.randrange(80, 86)
            y = random.randrange(15, 59)
        case 17: # More than 35 yards
            x = random.randrange(75, 80)
            y = random.randrange(15, 59)
        case 18: # More than 40 yards
            x = random.randrange(58, 75)
            y = random.randrange(15, 59)
    x_scaled = x / 115
    y_scaled = y / 74
    coordinates["x"].append(x_scaled)
    coordinates["y"].append(y_scaled)
final_df = filtered_df.assign(**coordinates)
final_df

,event_type,event_team,player,is_goal,location,date,season,x,y
8144,1,Real Madrid,Cristiano Ronaldo,0,3.0,2011-08-28,2012,0.878261,0.459459
8149,1,Real Madrid,Cristiano Ronaldo,0,15.0,2011-08-28,2012,0.826087,0.432432
8152,1,Real Madrid,Cristiano Ronaldo,1,3.0,2011-08-28,2012,0.878261,0.445946
8156,1,Real Madrid,Cristiano Ronaldo,0,15.0,2011-08-28,2012,0.773913,0.418919
8159,1,Real Madrid,Cristiano Ronaldo,0,3.0,2011-08-28,2012,0.939130,0.540541
...,...,...,...,...,...,...,...,...,...
939440,1,FC Barcelona,Lionel Messi,0,15.0,2017-01-22,2017,0.834783,0.702703
939457,1,FC Barcelona,Luis Suarez,0,9.0,2017-01-22,2017,0.878261,0.918919
939462,1,FC Barcelona,Lionel Messi,1,3.0,2017-01-22,2017,0.886957,0.513514
939471,1,FC Barcelona,Luis Suarez,1,11.0,2017-01-22,2017,0.860870,0.094595
939474,1,FC Barcelona,Luis Suarez,0,11.0,2017-01-22,2017,0.860870,0.040541

In [30]:
final_df.to_json("events.json", orient='records', indent=2)