In [15]:
import pandas as pd
from pathlib import Path

DATA_DIR = Path("datasets")
EVENTS_DIR = DATA_DIR.joinpath("events")
TRANSFERS_DIR = DATA_DIR.joinpath("transfers")


events_df = pd.read_csv(EVENTS_DIR.joinpath("events.csv"))
game_info_df = pd.read_csv(EVENTS_DIR.joinpath("ginf.csv"))
event_game_info_df = pd.merge(events_df, game_info_df, on='id_odsp', how='inner')
transfers_df = pd.read_csv(TRANSFERS_DIR.joinpath("transfers.csv"))

In [16]:
player_name = 'Zlatan Ibrahimovic'

In [17]:
player_event_game_info = event_game_info_df[event_game_info_df['player'] == player_name.lower()]
player_event_game_info

,id_odsp,id_event,sort_order,time,text,event_type,event_type2,side,event_team,opponent,...,at,fthg,ftag,odd_h,odd_d,odd_a,odd_over,odd_under,odd_bts,odd_bts_n
9315,W0scuwXc/,W0scuwXc18,18,20,Zlatan Ibrahimovic (Milan) wins a free kick on...,8,NaN,1,AC Milan,Lazio,...,Lazio,2,2,1.64,3.85,7.40,NaN,NaN,NaN,NaN
9320,W0scuwXc/,W0scuwXc23,23,21,"Offside, Milan. Antonio Cassano tries a throug...",9,13.0,1,AC Milan,Lazio,...,Lazio,2,2,1.64,3.85,7.40,NaN,NaN,NaN,NaN
9331,W0scuwXc/,W0scuwXc34,34,29,"Goal! Milan 1, Lazio 2. Zlatan Ibrahimovic (M...",1,12.0,1,AC Milan,Lazio,...,Lazio,2,2,1.64,3.85,7.40,NaN,NaN,NaN,NaN
9340,W0scuwXc/,W0scuwXc43,43,34,Foul by Zlatan Ibrahimovic (Milan).,3,NaN,1,AC Milan,Lazio,...,Lazio,2,2,1.64,3.85,7.40,NaN,NaN,NaN,NaN
9368,W0scuwXc/,W0scuwXc71,71,59,"Offside, Milan. Antonio Cassano tries a throug...",9,13.0,1,AC Milan,Lazio,...,Lazio,2,2,1.64,3.85,7.40,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938256,rTDhZYPk/,rTDhZYPk32,32,30,"Offside, Manchester United. Phil Jones tries a...",9,13.0,2,Manchester Utd,Stoke City,...,Manchester Utd,1,1,6.40,4.42,1.64,1.97,2.0,1.95,1.95
938281,rTDhZYPk/,rTDhZYPk60,60,47,"Offside, Manchester United. Henrikh Mkhitaryan...",9,13.0,2,Manchester Utd,Stoke City,...,Manchester Utd,1,1,6.40,4.42,1.64,1.97,2.0,1.95,1.95
938288,rTDhZYPk/,rTDhZYPk67,67,56,Zlatan Ibrahimovic (Manchester United) wins a ...,8,NaN,2,Manchester Utd,Stoke City,...,Manchester Utd,1,1,6.40,4.42,1.64,1.97,2.0,1.95,1.95
938290,rTDhZYPk/,rTDhZYPk69,69,58,"Offside, Manchester United. Paul Pogba tries a...",9,13.0,2,Manchester Utd,Stoke City,...,Manchester Utd,1,1,6.40,4.42,1.64,1.97,2.0,1.95,1.95
938294,rTDhZYPk/,rTDhZYPk73,73,61,Foul by Zlatan Ibrahimovic (Manchester United).,3,NaN,2,Manchester Utd,Stoke City,...,Manchester Utd,1,1,6.40,4.42,1.64,1.97,2.0,1.95,1.95

In [18]:
player_transfers = transfers_df[transfers_df['player_name'] == player_name]
player_transfers

,league,season,window,team_id,team_name,team_country,dir,player_id,player_name,player_age,...,counter_team_id,counter_team_name,counter_team_country,transfer_fee_amnt,market_val_amnt,is_free,is_loan,is_loan_end,is_retired,transfer_id
7035,GB1,2016,s,985,Manchester United,England,in,3455,Zlatan Ibrahimovic,34.0,...,583,Paris Saint-Germain,France,0.0,4000000.0,True,False,False,False,1519372
8352,GB1,2017,w,985,Manchester United,England,left,3455,Zlatan Ibrahimovic,36.0,...,1061,Los Angeles Galaxy,United States,0.0,4000000.0,True,False,False,False,2070239
11611,ES1,2009,s,131,FC Barcelona,Spain,in,3455,Zlatan Ibrahimovic,27.0,...,46,FC Internazionale,Italy,69500000.0,4000000.0,False,False,False,False,324955
12117,ES1,2010,s,131,FC Barcelona,Spain,left,3455,Zlatan Ibrahimovic,28.0,...,5,AC Milan,Italy,6000000.0,4000000.0,False,True,False,False,473616
12725,ES1,2011,s,131,FC Barcelona,Spain,in,3455,Zlatan Ibrahimovic,29.0,...,5,AC Milan,Italy,NaN,4000000.0,False,True,True,False,473617
12729,ES1,2011,s,131,FC Barcelona,Spain,left,3455,Zlatan Ibrahimovic,29.0,...,5,AC Milan,Italy,24000000.0,4000000.0,False,False,False,False,583543
19881,IT1,2009,s,46,FC Internazionale,Italy,left,3455,Zlatan Ibrahimovic,27.0,...,131,FC Barcelona,Spain,69500000.0,4000000.0,False,False,False,False,324955
21326,IT1,2010,s,5,AC Milan,Italy,in,3455,Zlatan Ibrahimovic,28.0,...,131,FC Barcelona,Spain,6000000.0,4000000.0,False,True,False,False,473616
22431,IT1,2011,s,5,AC Milan,Italy,in,3455,Zlatan Ibrahimovic,29.0,...,131,FC Barcelona,Spain,24000000.0,4000000.0,False,False,False,False,583543
22481,IT1,2011,s,5,AC Milan,Italy,left,3455,Zlatan Ibrahimovic,29.0,...,131,FC Barcelona,Spain,NaN,4000000.0,False,True,True,False,473617
23299,IT1,2012,s,5,AC Milan,Italy,left,3455,Zlatan Ibrahimovic,30.0,...,583,Paris Saint-Germain,France,21000000.0,4000000.0,False,False,False,False,751914
34017,IT1,2019,w,5,AC Milan,Italy,in,3455,Zlatan Ibrahimovic,38.0,...,1061,Los Angeles Galaxy,United States,0.0,4000000.0,True,False,False,False,2701191
45053,FR1,2012,s,583,Paris Saint-Germain,France,in,3455,Zlatan Ibrahimovic,30.0,...,5,AC Milan,Italy,21000000.0,4000000.0,False,False,False,False,751914
47100,FR1,2016,s,583,Paris Saint-Germain,France,left,3455,Zlatan Ibrahimovic,34.0,...,985,Manchester United,England,0.0,4000000.0,True,False,False,False,1519372

In [19]:
player_path_name = player_name.lower().replace(' ', '_')
player_event_game_info.to_json(EVENTS_DIR.joinpath(player_path_name).with_suffix('.json'))
player_transfers.to_json(TRANSFERS_DIR.joinpath(player_path_name).with_suffix('.json'))